import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const code=fs.readFileSync(new URL('../war-data.js',import.meta.url),'utf8');
function client(handler,{central=true,saved}={}){const disk=new Map(saved?[['hdbr_telemetry_v1:https://api.helldivers2.dev/api/v1/planets',JSON.stringify(saved)]]:[]),calls=[];
 const window={HDBRTelemetryConfig:{centralUrl:central?'https://central.example':'',timeoutMs:1000,directTimeoutMs:1000},addEventListener(){},dispatchEvent(){}};
 const context={window,document:{body:null,addEventListener(){}},location:{href:'https://helldivers-br.pages.dev/'},localStorage:{getItem:k=>disk.get(k)||null,setItem:(k,v)=>disk.set(k,v)},fetch:async(...args)=>{calls.push(args[0]);return handler(...args)},AbortController,Map,Set,Date,Number,Error,URL,Event,setTimeout,clearTimeout,console:{warn(){}}};vm.runInNewContext(code,context);return {api:window.HDBRWarData,disk,calls};
}
const url='https://api.helldivers2.dev/api/v1/planets',data=Array.from({length:10},(_,index)=>({index}));
test('cliente central: deduplica consultas e usa timestamp do servidor, não hora de download',async()=>{const stamp=Date.now()-60000,c=client(async()=>Response.json({data,time:stamp,stale:false,source:'direct',next:Date.now()+60000}));await Promise.all(Array.from({length:20},()=>c.api.get(url,'planets',60000,{})));assert.equal(c.calls.length,1);assert.equal(c.api.meta(url).time,stamp);assert.equal(c.api.meta(url).source,'direct')});
test('leitura stale da central permanece stale mesmo recém-baixada',async()=>{const stamp=Date.now()-120000,c=client(async()=>Response.json({data,time:stamp,stale:true,source:'direct',next:Date.now()+10000,error:'upstream timeout'}));await c.api.get(url,'planets');await c.api.get(url,'planets');assert.equal(c.calls.length,1);assert.equal(c.api.meta(url).stale,true);assert.equal(c.api.meta(url).time,stamp)});
test('falha da central preserva cache e não dispara consulta direta de cada visitante',async()=>{const stamp=Date.now()-120000,c=client(async()=>new Response('',{status:503}),{saved:{time:stamp,data,source:'direct'}});await c.api.get(url,'planets');assert.equal(c.api.meta(url).stale,true);assert.equal(c.api.meta(url).time,stamp);assert.equal(c.calls.length,1);assert.ok(c.calls[0].startsWith('https://central.example'));assert.equal(c.api.diagnostics()[0].status,503)});
test('cache expirado de mais de um dia não é apresentado como estado válido',async()=>{const c=client(async()=>new Response('',{status:503}),{saved:{time:Date.now()-90000000,data}});await assert.rejects(c.api.get(url,'planets'))});
test('central com timestamp futuro ou resposta inválida é rejeitada',async()=>{const c=client(async()=>Response.json({data,time:Date.now()+10000,stale:false,source:'direct'}));await assert.rejects(c.api.get(url,'planets'),/inválida/)});
test('modo anterior funciona sem Worker e guarda diagnóstico da Community',async()=>{const c=client(async()=>Response.json(data),{central:false});await c.api.get(url,'planets');assert.equal(c.api.meta(url).source,'community');assert.equal(c.api.diagnostics()[0].status,200)});
test('timeout real aborta a chamada e registra duração e origem',async()=>{const c=client((url,opts)=>new Promise((resolve,reject)=>opts.signal.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')))));await assert.rejects(c.api.get(url,'planets'),/Tempo limite/);assert.equal(c.api.diagnostics()[0].source,'central');assert.ok(c.api.diagnostics()[0].durationMs>=900)});
